### ISSUE TITLE
Make the licensing more explicite in the source files and probably add a copy of Apache 2 to the repo.

### ISSUE THREAD

**Issue by ninjaaron** [mikehearn/nodejs-interop#1]
Licensing need to by much more clear before anyone would use this in production.

**Comment by mikehearn** [comment]
I've added a LICENSE file.

**Comment by ninjaaron** [comment]
_ideally_, there would also be a license notice in source files, but adding the license file is a huge improvement. Thanks!

**Comment by mikehearn** [comment]
I know it's common but it makes no legal difference to put license info at the top of every file. That's not how copyright law is written.

**Comment by ninjaaron** [comment]
OK.
